vpc_cidr_block = "10.1.0.0/16"
subnet_cidr_block = "10.1.1.0/24"
avail_zone = "us-east-2b"
env_prefix = "qa"
my_ip = "52.14.135.171/32"
public_key_location = "/home/ec2-user/.ssh/id_rsa.pub"
instance_type = "t2.small"
ssh_key_private = "/home/ec2-user/.ssh/id_rsa"

# terraform apply -var-file="qa.tfvars"
